server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: event
        uri: lb://event/
        predicates:
          - Path=/event/**
      - id: cart
        uri: lb://user/
        predicates:
          - Path=/user/**
      - id: cartCB
        uri: lb://purchase/
        predicates:
          - Path=/purchase/**       
